### PR TITLE
Add Azure Blob Storage backend

### PR DESCRIPTION
**Pull request by christoe**
Hi!

I implemented support for Azure Blob Storage as a backend, inspired by the s3 and GS backends that already existed. I tried documenting and writing tests also based on what as available in the repo. Please get back to me if you have any feedback.

Thanks!

### CODE REVIEW

**Comment by christoe** [comment]
Hi @vincentsarago! Sorry for tagging you explicitly, but since you seem to be the main contributor - is this project still active?

**Comment by vincentsarago** [comment]
sorry @christoe, I am the main contributor and sadly I have a lot other priority right now :-(

**Comment by vincentsarago** [comment]
@christoe in order to allow the CI to run tests you must add `"az"` in https://github.com/developmentseed/cogeo-mosaic/blob/master/.github/workflows/ci.yml#L35 -> `python -m pip install -e .["test,az"]`

**Comment by christoe** [comment]
@vincentsarago Thanks and I totally understand. I was able to get the tests running now.

**Review by vincentsarago — APPROVED** [review]

**Pull request merged**
